export const API_CALL_ERROR = "API_CALL_ERROR";
export const BEGIN_API_CALL = "BEGIN_API_CALL";

export const LOAD_BOOKS_SUCCESS = "LOAD_BOOKS_SUCCESS";
export const LOAD_CHAPTERS_SUCCESS = "LOAD_CHAPTERS_SUCCESS";
