const testaments = [
  { id: 1, name: "Old Testament" },
  { id: 2, name: "New Testament" }
];

const books = [
  { id: 1, testamentId: 1, abbr: "Gen", name: "Genesis" },
  { id: 2, testamentId: 1, abbr: "Exo", name: "Exodus" },
  { id: 3, testamentId: 1, abbr: "Lev", name: "Leviticus" },
  { id: 4, testamentId: 1, abbr: "Num", name: "Numbers" },
  { id: 5, testamentId: 1, abbr: "Deu", name: "Deuteronomy" },
  { id: 6, testamentId: 1, abbr: "Jos", name: "Joshua" },
  { id: 7, testamentId: 1, abbr: "Judg", name: "Judges" },
  { id: 8, testamentId: 1, abbr: "Rth", name: "Ruth" },
  { id: 9, testamentId: 1, abbr: "1Sa", name: "1 Samuel" },
  { id: 10, testamentId: 1, abbr: "2Sa", name: "2 Samuel" },
  { id: 11, testamentId: 1, abbr: "1Ki", name: "1 Kings" },
  { id: 12, testamentId: 1, abbr: "2Ki", name: "2 Kings" },
  { id: 13, testamentId: 1, abbr: "1Ch", name: "1 Chronicles" },
  { id: 14, testamentId: 1, abbr: "2Ch", name: "2 Chronicles" },
  { id: 15, testamentId: 1, abbr: "Eza", name: "Ezra" },
  { id: 16, testamentId: 1, abbr: "Neh", name: "Nehemiah" },
  { id: 17, testamentId: 1, abbr: "Est", name: "Esther" },
  { id: 18, testamentId: 1, abbr: "Job", name: "Job" },
  { id: 19, testamentId: 1, abbr: "Psa", name: "Psalms" },
  { id: 20, testamentId: 1, abbr: "Pro", name: "Proverbs" },
  { id: 21, testamentId: 1, abbr: "Ecc", name: "Ecclesiastes" },
  { id: 22, testamentId: 1, abbr: "SS", name: "Song of Songs" },
  { id: 23, testamentId: 1, abbr: "Isa", name: "Isaiah" },
  { id: 24, testamentId: 1, abbr: "Jer", name: "Jeremiah" },
  { id: 25, testamentId: 1, abbr: "Lam", name: "Lamentations" },
  { id: 26, testamentId: 1, abbr: "Ezk", name: "Ezekiel" },
  { id: 27, testamentId: 1, abbr: "Dan", name: "Daniel" },
  { id: 28, testamentId: 1, abbr: "Hos", name: "Hosea" },
  { id: 29, testamentId: 1, abbr: "Joe", name: "Joel" },
  { id: 30, testamentId: 1, abbr: "Amo", name: "Amos" },
  { id: 31, testamentId: 1, abbr: "Obd", name: "Obadiah" },
  { id: 32, testamentId: 1, abbr: "Jon", name: "Jonah" },
  { id: 33, testamentId: 1, abbr: "Mic", name: "Micah" },
  { id: 34, testamentId: 1, abbr: "Nah", name: "Nahum" },
  { id: 35, testamentId: 1, abbr: "Hab", name: "Habakkuk" },
  { id: 36, testamentId: 1, abbr: "Zep", name: "Zephaniah" },
  { id: 37, testamentId: 1, abbr: "Hag", name: "Haggai" },
  { id: 38, testamentId: 1, abbr: "Zch", name: "Zechariah" },
  { id: 39, testamentId: 1, abbr: "Mal", name: "Malachi" },
  { id: 40, testamentId: 2, abbr: "Mat", name: "Matthew" },
  { id: 41, testamentId: 2, abbr: "Mar", name: "Mark" },
  { id: 42, testamentId: 2, abbr: "Luk", name: "Luke" },
  { id: 43, testamentId: 2, abbr: "Jn", name: "John" },
  { id: 44, testamentId: 2, abbr: "Act", name: "Acts" },
  { id: 45, testamentId: 2, abbr: "Rom", name: "Romans" },
  { id: 46, testamentId: 2, abbr: "1Co", name: "1 Corinthians" },
  { id: 47, testamentId: 2, abbr: "2Co", name: "2 Corinthians" },
  { id: 48, testamentId: 2, abbr: "Gal", name: "Galatians" },
  { id: 49, testamentId: 2, abbr: "Eph", name: "Ephesians" },
  { id: 50, testamentId: 2, abbr: "Phi", name: "Philippians" },
  { id: 51, testamentId: 2, abbr: "Col", name: "Colossians" },
  { id: 52, testamentId: 2, abbr: "1Th", name: "1 Thessalonians" },
  { id: 53, testamentId: 2, abbr: "2Th", name: "2 Thessalonians" },
  { id: 54, testamentId: 2, abbr: "1Ti", name: "1 Timothy" },
  { id: 55, testamentId: 2, abbr: "2Ti", name: "2 Timothy" },
  { id: 56, testamentId: 2, abbr: "Tit", name: "Titus" },
  { id: 57, testamentId: 2, abbr: "Phm", name: "Philemon" },
  { id: 58, testamentId: 2, abbr: "Heb", name: "Hebrews" },
  { id: 59, testamentId: 2, abbr: "Jam", name: "James" },
  { id: 60, testamentId: 2, abbr: "1Pe", name: "1 Peter" },
  { id: 61, testamentId: 2, abbr: "2Pe", name: "2 Peter" },
  { id: 62, testamentId: 2, abbr: "1Jo", name: "1 John" },
  { id: 63, testamentId: 2, abbr: "2Jo", name: "2 John" },
  { id: 64, testamentId: 2, abbr: "3Jo", name: "3 John" },
  { id: 65, testamentId: 2, abbr: "Jud", name: "Jude" },
  { id: 66, testamentId: 2, abbr: "Rev", name: "Revelation" }
];

const chapters = [
  { id: 1, bookId: 1, chapter: 1 },
  { id: 2, bookId: 1, chapter: 2 },
  { id: 3, bookId: 1, chapter: 3 },
  { id: 4, bookId: 1, chapter: 4 },
  { id: 5, bookId: 1, chapter: 5 },
  { id: 6, bookId: 1, chapter: 6 },
  { id: 7, bookId: 1, chapter: 7 },
  { id: 8, bookId: 1, chapter: 8 },
  { id: 9, bookId: 1, chapter: 9 },
  { id: 10, bookId: 1, chapter: 10 },
  { id: 11, bookId: 1, chapter: 11 },
  { id: 12, bookId: 1, chapter: 12 },
  { id: 13, bookId: 1, chapter: 13 },
  { id: 14, bookId: 1, chapter: 14 },
  { id: 15, bookId: 1, chapter: 15 },
  { id: 16, bookId: 1, chapter: 16 },
  { id: 17, bookId: 1, chapter: 17 },
  { id: 18, bookId: 1, chapter: 18 },
  { id: 19, bookId: 1, chapter: 19 },
  { id: 20, bookId: 1, chapter: 20 },
  { id: 21, bookId: 1, chapter: 21 },
  { id: 22, bookId: 1, chapter: 22 },
  { id: 23, bookId: 1, chapter: 23 },
  { id: 24, bookId: 1, chapter: 24 },
  { id: 25, bookId: 1, chapter: 25 },
  { id: 26, bookId: 1, chapter: 26 },
  { id: 27, bookId: 1, chapter: 27 },
  { id: 28, bookId: 1, chapter: 28 },
  { id: 29, bookId: 1, chapter: 29 },
  { id: 30, bookId: 1, chapter: 30 },
  { id: 31, bookId: 1, chapter: 31 },
  { id: 32, bookId: 1, chapter: 32 },
  { id: 33, bookId: 1, chapter: 33 },
  { id: 34, bookId: 1, chapter: 34 },
  { id: 35, bookId: 1, chapter: 35 },
  { id: 36, bookId: 1, chapter: 36 },
  { id: 37, bookId: 1, chapter: 37 },
  { id: 38, bookId: 1, chapter: 38 },
  { id: 39, bookId: 1, chapter: 39 },
  { id: 40, bookId: 1, chapter: 40 },
  { id: 41, bookId: 1, chapter: 41 },
  { id: 42, bookId: 1, chapter: 42 },
  { id: 43, bookId: 1, chapter: 43 },
  { id: 44, bookId: 1, chapter: 44 },
  { id: 45, bookId: 1, chapter: 45 },
  { id: 46, bookId: 1, chapter: 46 },
  { id: 47, bookId: 1, chapter: 47 },
  { id: 48, bookId: 1, chapter: 48 },
  { id: 49, bookId: 1, chapter: 49 },
  { id: 50, bookId: 1, chapter: 50 },
  { id: 51, bookId: 2, chapter: 1 },
  { id: 52, bookId: 2, chapter: 2 },
  { id: 53, bookId: 2, chapter: 3 },
  { id: 54, bookId: 2, chapter: 4 },
  { id: 55, bookId: 2, chapter: 5 },
  { id: 56, bookId: 2, chapter: 6 },
  { id: 57, bookId: 2, chapter: 7 },
  { id: 58, bookId: 2, chapter: 8 },
  { id: 59, bookId: 2, chapter: 9 },
  { id: 60, bookId: 2, chapter: 10 },
  { id: 61, bookId: 2, chapter: 11 },
  { id: 62, bookId: 2, chapter: 12 },
  { id: 63, bookId: 2, chapter: 13 },
  { id: 64, bookId: 2, chapter: 14 },
  { id: 65, bookId: 2, chapter: 15 },
  { id: 66, bookId: 2, chapter: 16 },
  { id: 67, bookId: 2, chapter: 17 },
  { id: 68, bookId: 2, chapter: 18 },
  { id: 69, bookId: 2, chapter: 19 },
  { id: 70, bookId: 2, chapter: 20 },
  { id: 71, bookId: 2, chapter: 21 },
  { id: 72, bookId: 2, chapter: 22 },
  { id: 73, bookId: 2, chapter: 23 },
  { id: 74, bookId: 2, chapter: 24 },
  { id: 75, bookId: 2, chapter: 25 },
  { id: 76, bookId: 2, chapter: 26 },
  { id: 77, bookId: 2, chapter: 27 },
  { id: 78, bookId: 2, chapter: 28 },
  { id: 79, bookId: 2, chapter: 29 },
  { id: 80, bookId: 2, chapter: 30 },
  { id: 81, bookId: 2, chapter: 31 },
  { id: 82, bookId: 2, chapter: 32 },
  { id: 83, bookId: 2, chapter: 33 },
  { id: 84, bookId: 2, chapter: 34 },
  { id: 85, bookId: 2, chapter: 35 },
  { id: 86, bookId: 2, chapter: 36 },
  { id: 87, bookId: 2, chapter: 37 },
  { id: 88, bookId: 2, chapter: 38 },
  { id: 89, bookId: 2, chapter: 39 },
  { id: 90, bookId: 2, chapter: 40 }
];
const verses = [
  {
    id: 1,
    chapterId: 1,
    verse: 1,
    text: "In the beginning God created the heaven and the earth."
  },
  {
    id: 2,
    chapterId: 1,
    verse: 2,
    text:
      "And the earth was without form and void; and darkness was upon the face of the deep. And the Spirit of God moved upon the face of the waters."
  },
  {
    id: 3,
    chapterId: 1,
    verse: 3,
    text: "And God said, Let there be light: and there was light."
  },
  {
    id: 4,
    chapterId: 1,
    verse: 4,
    text:
      "And God saw the light, that it was good: and God divided the light from the darkness."
  },
  {
    id: 5,
    chapterId: 1,
    verse: 5,
    text:
      "And God called the light Day, and the darkness he called Night. And the evening and the morning were the first day."
  }
];
const commentary = [];

// Using CommonJS style export so we can consume via Node (without using Babel-node)
module.exports = {
  testaments,
  books,
  chapters,
  verses,
  commentary
};
